#ifndef SPRITES_H
#define SPRITES_H

#include "types.h"


/*
Name: arsh_jump
Size: UINT32
Width: 64
Height: 96
*/
extern const UINT32 bmp_arsh_jump_64 [];


/*
Name: arsh_kick
Size: UINT32
Width: 64
Height: 96
*/
extern const UINT32 bmp_arsh_kick_64 [];


/*
Name: arsh_run
Size: UINT32
Width: 64
Height: 96
*/
extern const UINT32 bmp_arsh_run_64 [];


/*
Name: arsh_run_2
Size: UINT32
Width: 64
Height: 96
*/
extern const UINT32 bmp_arsh_run_2_64 [];


/*
Name: arsh_slide
Size: UINT32
Width: 96
Height: 60
*/
extern const UINT32 bmp_arsh_slide_96 [];


/*
Name: bad_bandit_run_64
Size: UINT32
Width: 64
Height: 96
*/
extern const UINT32 bmp_bad_bandit_run_64 [];


/*
Name: bad_bandit_run_2_64
Size: UINT32
Width: 64
Height: 96
*/
extern const UINT32 bmp_bad_bandit_run_2_64 [];


/*
Name: bad_bandit_jump_64
Size: UINT32
Width: 64
Height: 96
*/
extern const UINT32 bmp_bad_bandit_jump_64 [];

/*
Name: bad_bandit_kick_64
Size: UINT32
Width: 64
Height: 96
*/
extern const UINT32 bmp_bad_bandit_kick_64 [];


/*
Name: bad_bandit_slide_96
Size: UINT32
Width: 96
Height: 60
*/
extern const UINT32 bmp_bad_bandit_slide_96 [];


/*
Name: cactus_32
Size: UINT32
Width: 32
Height: 128
*/
extern const UINT32 bmp_cactus_32 [];


/*
Name: cactus_dead_32
Size: UINT32
Width: 32
Height: 53
*/
extern const UINT32 bmp_cactus_dead_32 [];


/*
Name: cloud
Size: UINT32
Width: 64
Height: 45
*/
extern const UINT32 bmp_cloud_64 [];


/*
Name: haybale_64
Size: UINT32
Width: 64
Height: 64
*/
extern const UINT32 bmp_haybale_64 [];


/*
Name: tumbleweed
Size: UINT32
Width: 64
Height: 64
*/
extern const UINT32 bmp_tumbleweed_64 [];


/*
Name: vulture_64
Size: UINT32
Width: 64
Height: 33
*/
extern const UINT32 bmp_vulture_64 [];


/*
Name: sun
Size: UINT32
Width: 64
Height: 64
*/
extern const UINT32 bmp_sun_64 [];


/*
Name: bmp_respect
Size: UINT32
Width: 64
Height: 14
*/
extern const UINT32 bmp_respect_64 [];


/*
Name: select_arrow
Size: UINT8
Width: 8
Height: 9
*/
extern const UINT8 bmp_select_arrow [];


/*
Name: menu
Size: UINT32
Width: 640
Height: 400
*/
extern const UINT32 bmp_menu [];


#endif